seed = 42
kg_csv = ""
kg_pkl = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL1experiment/withoutDL1/kg_processing/kgate/"
metadata_csv = ""
output_directory = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL1experiment/withoutDL1/models/run2/GCN_RESCAL/"
verbose = true
run_kg_preprocessing = false

[preprocessing]
remove_duplicate_triplets = true
make_directed = true
flag_near_duplicate_edges = true
clean_train_set = true
make_directed_edges = []
split = [
    0.8,
    0.1,
    0.1,
]

[preprocessing.params]
theta = 0.8
theta_second_edge_type = 0.8
theta_first_edge_type = 0.8

[model]
edge_embedding_dimensions = -1
node_embedding_dimensions = 200

[model.decoder]
name = "RESCAL"
dissimilarity = "L2"
margin = 1
filter_count = 3

[model.encoder]
name = "GCN"
gnn_layer_number = 1

[sampler]
name = "Mixed"
negative_triplet_count = 5

[optimizer]
name = "Adam"

[optimizer.params]
lr = 0.001
weight_decay = 0.001

[learning_rate_scheduler]
type = "CosineAnnealingWarmRestarts"

[learning_rate_scheduler.params]
T_0 = 10
T_mult = 2

[training]
save_interval = 2
max_epochs = 250
pretrained_embeddings = "auto"
train_batch_size = 4096
evaluation_batch_size = 256
patience = 5
evaluation_interval = 10

[evaluation]
inference_kg = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/knowledge_graph/orphan_associations.tsv"
made_directed_edges = [
    "drug_drug",
    "disease_disease",
    "protein_protein",
    "drug_drug_inv",
    "disease_disease_inv",
    "protein_protein_inv",
]
objective = "Link Prediction"
target_edges = [
    "indication",
]
thresholds = [
    10,
    5,
]

[data_leakage]
permuted_edges = []
