Global_metrics = 0.0785265676677227

[target_edges]
Global_metrics = 64.54883862286806

[target_edges.Individual_metrics]
DRUG_DISEASE_ASSOCIATION = 0.0785265676677227

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
