Global_metrics = 0.07437599822878838

[target_edges]
Global_metrics = 61.137070544064045

[target_edges.Individual_metrics]
DRUG_DISEASE_ASSOCIATION = 0.07437599822878838

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
