Global_metrics = 0.020017954928334802

[target_edges]
Global_metrics = 18.91696740727639

[target_edges.Individual_metrics]
DRUG_DISEASE_ASSOCIATION = 0.020017954928334802

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
