seed = 42
kg_csv = ""
kg_pkl = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL3experiment/cold_start/biokg_processing_disease/kgate/"
metadata_csv = ""
output_directory = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL3experiment/cold_start/models_diseases_biokg/run2/GCN_RESCAL/"
verbose = true
run_kg_preprocessing = false

[preprocessing]
remove_duplicate_triplets = true
make_directed = true
clean_train_set = true
flag_near_duplicate_edges = true
split = [
    0.8,
    0.1,
    0.1,
]
make_directed_edges = []

[preprocessing.params]
theta_second_edge_type = 0.8
theta = 0.8
theta_first_edge_type = 0.8

[model]
node_embedding_dimensions = 200
edge_embedding_dimensions = -1

[model.encoder]
name = "GCN"
gnn_layer_number = 1

[model.decoder]
name = "RESCAL"
dissimilarity = "L2"
filter_count = 3
margin = 1

[sampler]
name = "Mixed"
negative_triplet_count = 5

[optimizer]
name = "Adam"

[optimizer.params]
lr = 0.001
weight_decay = 0.001

[learning_rate_scheduler]
type = "CosineAnnealingWarmRestarts"

[learning_rate_scheduler.params]
T_mult = 2
T_0 = 10

[training]
evaluation_interval = 10
patience = 5
save_interval = 5
pretrained_embeddings = "auto"
train_batch_size = 4096
max_epochs = 250
evaluation_batch_size = 256

[evaluation]
objective = "Link Prediction"
target_edges = [
    "DRUG_DISEASE_ASSOCIATION",
]
inference_kg = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/knowledge_graph/biokg_orphan_associations_only.tsv"
thresholds = [
    10,
    5,
]
made_directed_edges = [
    "DDI",
    "PPI",
    "DDI_inv",
    "PPI_inv",
    "DPI",
    "DRUG_TARGET",
]

[data_leakage]
permuted_edges = []
