seed = 42
kg_csv = ""
kg_pkl = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL3experiment/cold_start/kg_processing_disease/kgate/"
metadata_csv = ""
output_directory = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL3experiment/cold_start/models_disease/run1/GCN_RESCAL_maxIntra/"
verbose = true
run_kg_preprocessing = false

[preprocessing]
make_directed = true
make_directed_edges = []
flag_near_duplicate_edges = true
remove_duplicate_triplets = true
split = [
    0.8,
    0.1,
    0.1,
]
clean_train_set = true

[preprocessing.params]
theta_second_edge_type = 0.8
theta = 0.8
theta_first_edge_type = 0.8

[model]
edge_embedding_dimensions = -1
node_embedding_dimensions = 200

[model.decoder]
dissimilarity = "L2"
filter_count = 3
name = "RESCAL"
margin = 1

[model.encoder]
neighbor_aggregation = "max"
gnn_layer_number = 1
name = "GCN"

[sampler]
negative_triplet_count = 5
name = "Mixed"

[optimizer]
name = "Adam"

[optimizer.params]
lr = 0.001
weight_decay = 0.001

[learning_rate_scheduler]
type = ""

[learning_rate_scheduler.params]

[training]
max_epochs = 250
train_batch_size = 4096
evaluation_batch_size = 256
pretrained_embeddings = "auto"
save_interval = 5
patience = 5
evaluation_interval = 10

[evaluation]
target_edges = [
    "indication",
]
inference_kg = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/knowledge_graph/orphan_associations.tsv"
thresholds = [
    10,
    5,
]
made_directed_edges = [
    "drug_drug",
    "disease_disease",
    "protein_protein",
    "drug_drug_inv",
    "disease_disease_inv",
    "protein_protein_inv",
]
objective = "Link Prediction"

[data_leakage]
permuted_edges = []
