common:
  seed: 42
  input_csv: "knowledge_graph/biokg_without_orphan_associations.tsv"
  out: "DL3experiment/cold_start/biokg_processing_disease/"
  run_kg_prep: true
  run_training: false
  run_evaluation: false

clean_kg:   
  remove_duplicates_triplets: true 

  make_directed: true
  make_directed_params: 
    - "DDI"
    - "PPI"

  check_DL1: true 
  check_DL1_params:
    theta1: 0.5
    theta2: 0.5
    theta: 0.5

  permute_kg: false

  cold_start_split: 'tail'
  cold_start_split_param: "DRUG_DISEASE_ASSOCIATION"

  clean_train_set: true
