Global_metrics = 0.030401970958337188

[target_edges]
Global_metrics = 30.858000522712246

[target_edges.Individual_metrics]
indication = 0.030401970958337188

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
