Global_metrics = 0.2302440507337451

[target_edges]
Global_metrics = 15.426351399160922

[target_edges.Individual_metrics]
CtD = 0.2302440507337451

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
