seed = 42
kg_csv = ""
kg_pkl = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL3experiment/cold_start/kg_processing_disease/kgate/"
metadata_csv = ""
output_directory = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL3experiment/cold_start/models_disease/run1/GAT_RESCAL/"
verbose = true
run_kg_preprocessing = false

[preprocessing]
flag_near_duplicate_edges = true
clean_train_set = true
remove_duplicate_triplets = true
make_directed_edges = []
make_directed = true
split = [
    0.8,
    0.1,
    0.1,
]

[preprocessing.params]
theta_first_edge_type = 0.8
theta = 0.8
theta_second_edge_type = 0.8

[model]
node_embedding_dimensions = 200
edge_embedding_dimensions = -1

[model.decoder]
name = "RESCAL"
margin = 1
dissimilarity = "L2"
filter_count = 3

[model.encoder]
name = "GAT"
gnn_layer_number = 1

[sampler]
name = "Mixed"
negative_triplet_count = 5

[optimizer]
name = "Adam"

[optimizer.params]
weight_decay = 0.001
lr = 0.001

[learning_rate_scheduler]
type = ""

[learning_rate_scheduler.params]

[training]
train_batch_size = 4096
save_interval = 5
evaluation_batch_size = 256
max_epochs = 250
patience = 5
evaluation_interval = 10
pretrained_embeddings = "auto"

[evaluation]
inference_kg = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/knowledge_graph/orphan_associations.tsv"
target_edges = [
    "indication",
]
objective = "Link Prediction"
thresholds = [
    10,
    5,
]
made_directed_edges = [
    "drug_drug",
    "disease_disease",
    "protein_protein",
    "drug_drug_inv",
    "disease_disease_inv",
    "protein_protein_inv",
]

[data_leakage]
permuted_edges = []
