Global_metrics = 0.0

[target_edges]
Global_metrics = 31.09994931226538

[target_edges.Individual_metrics]
indication = 0.030640344150015153

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
