Global_metrics = 0.04722394794225693

[target_edges]
Global_metrics = 47.93230716139078

[target_edges.Individual_metrics]
indication = 0.04722394794225693

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
