Global_metrics = 0.06530517712235451

[target_edges]
Global_metrics = 53.680855594575405

[target_edges.Individual_metrics]
DRUG_DISEASE_ASSOCIATION = 0.06530517712235451

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
