Global_metrics = 0.06382312159985304

[target_edges]
Global_metrics = 52.4626059550792

[target_edges.Individual_metrics]
DRUG_DISEASE_ASSOCIATION = 0.06382312159985304

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
