Global_metrics = 0.004437753697857261

[target_edges]
Global_metrics = 3.643395785940811

[target_edges.Individual_metrics]
indication = 0.004437753697857261

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
