Global_metrics = 0.02897223160834983

[target_edges]
Global_metrics = 27.37875886989059

[target_edges.Individual_metrics]
DRUG_DISEASE_ASSOCIATION = 0.02897223160834983

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
