Global_metrics = 0.02537727972958237

[target_edges]
Global_metrics = 25.757938925526105

[target_edges.Individual_metrics]
indication = 0.02537727972958237

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
