seed = 42
kg_csv = ""
kg_pkl = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL1experiment/withDL1/kg_processing/kgate/"
metadata_csv = ""
output_directory = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL1experiment/withDL1/models/run1/GAT_RESCAL/"
verbose = true
run_kg_preprocessing = false

[preprocessing]
split = [
    0.8,
    0.1,
    0.1,
]
make_directed_edges = []
clean_train_set = true
make_directed = true
flag_near_duplicate_edges = true
remove_duplicate_triplets = true

[preprocessing.params]
theta = 0.8
theta_second_edge_type = 0.8
theta_first_edge_type = 0.8

[model]
edge_embedding_dimensions = -1
node_embedding_dimensions = 200

[model.encoder]
name = "GAT"
gnn_layer_number = 1

[model.decoder]
name = "RESCAL"
filter_count = 3
dissimilarity = "L2"
margin = 1

[sampler]
name = "Mixed"
negative_triplet_count = 5

[optimizer]
name = "Adam"

[optimizer.params]
lr = 0.001
weight_decay = 0.001

[learning_rate_scheduler]
type = ""

[learning_rate_scheduler.params]

[training]
evaluation_interval = 10
pretrained_embeddings = "auto"
max_epochs = 250
evaluation_batch_size = 256
train_batch_size = 4096
save_interval = 2
patience = 5

[evaluation]
objective = "Link Prediction"
made_directed_edges = [
    "drug_drug",
    "disease_disease",
    "protein_protein",
    "drug_drug_inv",
    "disease_disease_inv",
    "protein_protein_inv",
]
thresholds = [
    10,
    5,
]
target_edges = [
    "indication",
]
inference_kg = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/knowledge_graph/orphan_associations.tsv"

[data_leakage]
permuted_edges = []
