seed = 42
kg_csv = ""
kg_pkl = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL1experiment/withoutDL1/hetionet_processing/kgate/"
metadata_csv = ""
output_directory = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL1experiment/withoutDL1/models_hetionet/run1/GCN_RESCAL_maxIntra/"
verbose = true
run_kg_preprocessing = false

[preprocessing]
make_directed = true
clean_train_set = true
flag_near_duplicate_edges = true
make_directed_edges = []
remove_duplicate_triplets = true
split = [
    0.8,
    0.1,
    0.1,
]

[preprocessing.params]
theta_first_edge_type = 0.8
theta = 0.8
theta_second_edge_type = 0.8

[model]
node_embedding_dimensions = 200
edge_embedding_dimensions = -1

[model.encoder]
name = "GCN"
neighbor_aggregation = "max"
gnn_layer_number = 1

[model.decoder]
filter_count = 3
name = "RESCAL"
dissimilarity = "L2"
margin = 1

[sampler]
negative_triplet_count = 5
name = "Mixed"

[optimizer]
name = "Adam"

[optimizer.params]
weight_decay = 0.001
lr = 0.001

[learning_rate_scheduler]
type = ""

[learning_rate_scheduler.params]

[training]
patience = 5
save_interval = 2
max_epochs = 250
train_batch_size = 4096
evaluation_batch_size = 256
pretrained_embeddings = "auto"
evaluation_interval = 10

[evaluation]
thresholds = [
    10,
    5,
]
target_edges = [
    "CtD",
]
inference_kg = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/knowledge_graph/hetionet_orphan_associations_only.tsv"
made_directed_edges = [
    "DrD",
    "DrD_inv",
    "CrC",
    "CrC_inv",
    "GiG",
    "GiG_inv",
    "GcG",
    "GcG_inv",
]
objective = "Link Prediction"

[data_leakage]
permuted_edges = []
