Global_metrics = 0.013608404202386737

[target_edges]
Global_metrics = 13.812530265422538

[target_edges.Individual_metrics]
indication = 0.013608404202386737

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
