seed = 42
kg_csv = ""
kg_pkl = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL2experiment/biokg_processing/kgate/"
metadata_csv = ""
output_directory = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL2experiment/models_biokg/run2/GAT_RESCAL/"
verbose = true
run_kg_preprocessing = false

[preprocessing]
remove_duplicate_triplets = true
clean_train_set = true
make_directed = true
split = [
    0.8,
    0.1,
    0.1,
]
make_directed_edges = []
flag_near_duplicate_edges = true

[preprocessing.params]
theta_first_edge_type = 0.8
theta_second_edge_type = 0.8
theta = 0.8

[model]
edge_embedding_dimensions = -1
node_embedding_dimensions = 200

[model.decoder]
margin = 1
name = "RESCAL"
filter_count = 3
dissimilarity = "L2"

[model.encoder]
gnn_layer_number = 1
name = "GAT"

[sampler]
name = "Mixed"
negative_triplet_count = 5

[optimizer]
name = "Adam"

[optimizer.params]
lr = 0.001
weight_decay = 0.001

[learning_rate_scheduler]
type = "CosineAnnealingWarmRestarts"

[learning_rate_scheduler.params]
T_mult = 2
T_0 = 10

[training]
save_interval = 5
evaluation_batch_size = 256
evaluation_interval = 10
max_epochs = 250
train_batch_size = 4096
patience = 5
pretrained_embeddings = "auto"

[evaluation]
thresholds = [
    10,
    5,
]
target_edges = [
    "DRUG_DISEASE_ASSOCIATION",
]
made_directed_edges = [
    "DDI",
    "PPI",
    "DDI_inv",
    "PPI_inv",
    "DPI",
    "DRUG_TARGET",
]
objective = "Link Prediction"
inference_kg = "/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/knowledge_graph/biokg_orphan_associations_only.tsv"

[data_leakage]
permuted_edges = []
