Global_metrics = 0.016969011398032308

[target_edges]
Global_metrics = 17.223546569002792

[target_edges.Individual_metrics]
indication = 0.016969011398032308

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
