common:
  seed: 42
  input_pkl: '/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/DL1experiment/withoutDL1/tarKG_processing/kg.pkl'
  out: './'
  run_kg_prep: false
  run_training: false
  run_evaluation: true
  plot_training_metrics: true
  run_inference: '/lustre/fswork/projects/rech/rnk/ufq76hz/dr_benchmark/knowledge_graph/TarKG_orphan_associations.tsv'

model:
  name: "TransD"               
  emb_dim: 200
  margin: 1                  

sampler:
  name: 'Mixed'
  n_neg: 5

optimizer:
  name: "Adam"
  params:
    lr: 0.001
    weight_decay: 0.001                        

lr_scheduler:  # Learning rate scheduler
  type: "CosineAnnealingWarmRestarts"  # Scheduler type (any from Pytorch)
  params:
    T_0: 10  # First cycle length
    T_mult: 2  # Multiplicative factor for cycle length

training:
  max_epochs: 500              
  batch_size: 4096     
  eval_interval: 20
  eval_batch_size: 16
  patience: 10

evaluation:
  made_directed_relations: ['Compound ddi Compound', 'Compound synergistic interaction Compound',"Compound associated with Compound","Compound compare Compound","Compound ddi Compound","Compound negative correlate Compound","Compound positive correlate Compound","Compound resembles Compound","Compound synergistic interaction Compound","Disease associated with Disease","Disease resembles Disease","Gene associated with Gene","Gene binds Gene","Gene colocalization Gene","Gene covaries Gene","Gene host microbiome interaction Gene","Gene negative correlate Gene","Gene other Gene","Gene physical association Gene","Gene positive correlate Gene","Gene ppi Gene","Gene relationships involving regulation and pathways Gene","Gene same protein or complex Gene","Gene signaling pathway Gene"]
  target_relations: ["Compound indication Disease", "Compound indication Disease"]
  thresholds: [10, 5]
