common:
  seed: 42
  input_csv: "/home/galadriel/dr_benchmark/knowledge_graph/shep_kg_without_orphan_treatments.csv"
  out: "/home/galadriel/dr_benchmark/DL3experiment/zero_shot/kg_processing_disease/"
  run_kg_prep: true
  run_training: false
  run_evaluation: false

clean_kg:   
  remove_duplicates_triplets: true 

  make_directed: true
  make_directed_params: 
    - "disease_disease"
    - "drug_drug"
    - "protein_protein"

  check_DL1: true 
  check_DL1_params:
    theta1: 0.8
    theta2: 0.8

  permute_kg: false

  cold_start_split: 'tail'
  cold_start_split_param: "indication"

  clean_train_set: true
