Global_metrics = 0.00515107880346477

[target_edges]
Global_metrics = 4.229035697644576

[target_edges.Individual_metrics]
indication = 0.00515107880346477

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
