Global_metrics = 0.013867350586224347

[target_edges]
Global_metrics = 13.104646303982008

[target_edges.Individual_metrics]
DRUG_DISEASE_ASSOCIATION = 0.013867350586224347

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
