Global_metrics = 0.10564816743135452

[target_edges]
Global_metrics = 11.304353915154934

[target_edges.Individual_metrics]
CtD = 0.10564816743135452

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
