Global_metrics = 0.038958142104092985

[target_edges]
Global_metrics = 36.81544428836787

[target_edges.Individual_metrics]
DRUG_DISEASE_ASSOCIATION = 0.038958142104092985

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
