Global_metrics = 0.1481092981994152

[target_edges]
Global_metrics = 15.847694907337427

[target_edges.Individual_metrics]
CtD = 0.1481092981994152

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
