Global_metrics = 0.03506987972650677

[target_edges]
Global_metrics = 33.1410363415489

[target_edges.Individual_metrics]
DRUG_DISEASE_ASSOCIATION = 0.03506987972650677

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
