Global_metrics = 0.1307195732370019

[target_edges]
Global_metrics = 13.986994336359203

[target_edges.Individual_metrics]
CtD = 0.1307195732370019

[remaining_edges]
Global_metrics = 0

[remaining_edges.Individual_metrics]

[target_edges_by_frequency]
